<?php

/**
 * @file
 * Contains dbtests.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

function dbtests_theme($existing, $type, $theme, $path) {
  return array(
    'dbtests' => array(
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_help().
 */
function dbtests_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dbTests module.
    case 'help.page.dbtests':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides D3 rendering of Test Viruses.') . '</p>';
      return $output;

    default:
  }
}